In [34]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import SGD
import os
import cv2
import random

In [25]:
#%%
file_dir='train'
cats =  []
label_cats = []
dogs = []
label_dogs = []
for file in os.listdir(file_dir):#返回這個路徑下所有檔案的名字
    name = file.split(sep='.')
    if name[0]=='cat':
        cats.append(file)
        label_cats.append(0)
    else:
        dogs.append(file)
        label_dogs.append(1)
print('there are %d cats\nthere are %d dogs' %(len(cats),len(dogs)))
image_list = np.hstack((cats, dogs))#將貓狗圖片堆積起來
label_list = np.hstack((label_cats,label_dogs))#label也堆積起來
temp = np.array([image_list,label_list])
temp = temp.transpose()
np.random.shuffle(temp)#打亂資料
image_list = list(temp[:,0])
label_list = list(temp[:,1])



there are 4 cats
there are 4 dogs


In [29]:
label_list = [int(i) for i in label_list]

In [20]:
print(cats,label_cats)
print(dogs,label_dogs)

['cat.0.jpg', 'cat.1.jpg', 'cat.2.jpg', 'cat.3.jpg'] [0, 0, 0, 0]
['dog.0.jpg', 'dog.1.jpg', 'dog.2.jpg', 'dog.3.jpg'] [1, 1, 1, 1]


In [15]:
print(label_list)
print(image_list)

[0 0 0 0 1 1 1 1]
['cat.0.jpg' 'cat.1.jpg' 'cat.2.jpg' 'cat.3.jpg' 'dog.0.jpg' 'dog.1.jpg'
 'dog.2.jpg' 'dog.3.jpg']


In [17]:
print(temp)

[['cat.0.jpg' 'cat.1.jpg' 'cat.2.jpg' 'cat.3.jpg' 'dog.0.jpg' 'dog.1.jpg'
  'dog.2.jpg' 'dog.3.jpg']
 ['0' '0' '0' '0' '1' '1' '1' '1']]


In [19]:
print(temp)

[['cat.0.jpg' '0']
 ['cat.1.jpg' '0']
 ['cat.2.jpg' '0']
 ['cat.3.jpg' '0']
 ['dog.0.jpg' '1']
 ['dog.1.jpg' '1']
 ['dog.2.jpg' '1']
 ['dog.3.jpg' '1']]


In [27]:
print(temp)

[['dog.1.jpg' '1']
 ['cat.2.jpg' '0']
 ['cat.1.jpg' '0']
 ['cat.3.jpg' '0']
 ['dog.3.jpg' '1']
 ['dog.2.jpg' '1']
 ['dog.0.jpg' '1']
 ['cat.0.jpg' '0']]


In [32]:
print(image_list)

['dog.1.jpg', 'cat.2.jpg', 'cat.1.jpg', 'cat.3.jpg', 'dog.3.jpg', 'dog.2.jpg', 'dog.0.jpg', 'cat.0.jpg']


In [26]:
print(label_list)

['1', '0', '0', '0', '1', '1', '1', '0']


In [31]:
print(label_list)

[1, 0, 0, 0, 1, 1, 1, 0]


In [41]:
print(image_list)

['dog.1.jpg', 'cat.2.jpg', 'cat.1.jpg', 'cat.3.jpg', 'dog.3.jpg', 'dog.2.jpg', 'dog.0.jpg', 'cat.0.jpg']


In [42]:
x_train=[]
y_train=label_list
path=os.path.join('train')
for j in image_list:
    img=cv2.imread(os.path.join(path,j),cv2.IMREAD_GRAYSCALE)
    nimg=cv2.resize(img,dsize=(150,150))
    x_train.append(nimg)

In [45]:
print(x_train)

[array([[ 54,  54,  57, ..., 109, 108, 106],
       [ 55,  55,  58, ..., 123, 122, 120],
       [ 55,  56,  61, ..., 136, 133, 131],
       ...,
       [230, 216, 220, ..., 123, 121, 118],
       [222, 220, 231, ..., 123, 118, 113],
       [222, 222, 212, ..., 121, 116, 109]], dtype=uint8), array([[ 62,  59,  50, ...,   7,   7,   7],
       [ 58,  62,  56, ...,   7,   7,   7],
       [ 59,  65,  64, ...,   7,   7,   7],
       ...,
       [ 57,  53,  67, ..., 240, 234, 234],
       [ 58,  53,  61, ..., 239, 237, 237],
       [ 59,  51,  58, ..., 237, 238, 238]], dtype=uint8), array([[ 44,  45,  44, ...,   2,   4,   4],
       [ 43,  45,  48, ...,   4,   4,   4],
       [ 42,  45,  48, ...,   4,   4,   4],
       ...,
       [146, 147, 147, ...,  96,  90,  82],
       [144, 145, 144, ...,  93,  90,  82],
       [139, 144, 144, ...,  92,  88,  81]], dtype=uint8), array([[ 53,  62,  65, ...,  83,  81,  80],
       [ 53,  62,  65, ...,  83,  81,  80],
       [ 56,  64,  65, ...,  83,  81, 

In [46]:
print(y_train)

[1, 0, 0, 0, 1, 1, 1, 0]


In [47]:
x_train=np.array(x_train).reshape(-1,150,150,1)
x_train=x_train/255

In [48]:
x_train.shape #25000筆,150x150的照片,1個Channel灰階

(8, 150, 150, 1)

In [49]:
x_train[5].shape

(150, 150, 1)

In [50]:
y_train= np.array(y_train)
y_train[5]

1

In [51]:
print(len(y_train),len(x_train))

8 8


In [52]:
print(x_train)

[[[[0.21176471]
   [0.21176471]
   [0.22352941]
   ...
   [0.42745098]
   [0.42352941]
   [0.41568627]]

  [[0.21568627]
   [0.21568627]
   [0.22745098]
   ...
   [0.48235294]
   [0.47843137]
   [0.47058824]]

  [[0.21568627]
   [0.21960784]
   [0.23921569]
   ...
   [0.53333333]
   [0.52156863]
   [0.51372549]]

  ...

  [[0.90196078]
   [0.84705882]
   [0.8627451 ]
   ...
   [0.48235294]
   [0.4745098 ]
   [0.4627451 ]]

  [[0.87058824]
   [0.8627451 ]
   [0.90588235]
   ...
   [0.48235294]
   [0.4627451 ]
   [0.44313725]]

  [[0.87058824]
   [0.87058824]
   [0.83137255]
   ...
   [0.4745098 ]
   [0.45490196]
   [0.42745098]]]


 [[[0.24313725]
   [0.23137255]
   [0.19607843]
   ...
   [0.02745098]
   [0.02745098]
   [0.02745098]]

  [[0.22745098]
   [0.24313725]
   [0.21960784]
   ...
   [0.02745098]
   [0.02745098]
   [0.02745098]]

  [[0.23137255]
   [0.25490196]
   [0.25098039]
   ...
   [0.02745098]
   [0.02745098]
   [0.02745098]]

  ...

  [[0.22352941]
   [0.20784314]
   [0.2

In [53]:
model = Sequential()

model.add(Conv2D(32,(3,3),input_shape=(150,150,1),padding='same',activation ='relu'))
model.add(MaxPooling2D(pool_size = (2,2)))

model.add(Conv2D(64,(3,3),padding='same',activation ='relu'))
model.add(MaxPooling2D(pool_size = (2,2)))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


In [54]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 150, 150, 32)      320       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 75, 75, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 75, 75, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 37, 37, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 87616)             0         
_________________________________________________________________
dense (Dense)                (None, 64)                5607488   
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 6

In [55]:
model.compile(optimizer='adam', #或是optimizer="adam" 
              loss='binary_crossentropy',metrics=['accuracy'])

In [56]:
model.fit(x_train,y_train, epochs=3, batch_size=100)

Train on 8 samples
Epoch 1/3
8/8 [==============================] - 1s 181ms/sample - loss: 0.7255 - accuracy: 0.5000
Epoch 2/3
8/8 [==============================] - 0s 19ms/sample - loss: 0.5928 - accuracy: 0.5000
Epoch 3/3
8/8 [==============================] - 0s 19ms/sample - loss: 0.3711 - accuracy: 1.0000
